import Nav from "@/components/Nav";
import "./globals.css";

export const metadata = {
  title: "Bitbank",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="min-h-screen bg-gradient-to-b from-gray-900 via-[#300171] to-slate-900 overflow-x-hidden">
        <Nav />
        {children}
      </body>
    </html>
  );
}
